### ISSUE TITLE
Very High Resolution

### ISSUE THREAD

**Issue by lolz0r** [kaishengtai/neuralart#11]
Hi,
This is very cool tech! I was curious if any thought had been put into how to make this approach to scale to higher resolutions; either by a CPU implementation or better yet have it work across multiple GPUs. 

If you have any insight please let me know.

Thanks,
Michael

**Comment by ryanpamplin** [comment]
Hi there. I would also love to make higher resolution images. I've tried many things including commenting out the Cuda calls and splitting images into smaller slices, but I haven't been able to make it work.

P.S.
Amazing work you've done! I've put many hours into playing with this and have created some incredibly cool art with it already. I can hardly wait to make bigger images. Thank you so much!

**Comment by kaishengtai** [comment]
I added CPU support in the [latest commit](https://github.com/kaishengtai/neuralart/commit/96077eeaeb6bbaecd97fdaed1d3eaa49e7f8c98c), so it should now scale to high-resolution images (though it'll take a long time to run).

I think that a tiling approach as suggested should allow for scaling to higher resolutions on GPU (and might even allow for optimization on multiple GPUs). I'll work on this next when I have time.

@ryanpamplin Thanks for the kind words!

**Comment by lolz0r** [comment]
@kaishengtai Nice work on the CPU only mode! I am running the latest code on a AWS node without any GPU and while I installed the cuda toolkit to compile inn and it's depencities when I try to actually run the applicaiton I get the following error:

 qlua main.lua --style VanGogh-starry_night_ballance1.jpg --content SEA-pic.jpg --style_factor 2E10  --display_interval 0 --optimizer lbfgs --cpu

It stops with the following error:
qlua: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-476/cutorch/lib/THC/THCGeneral.c:16

It looks like it is trying to include cuda related things even though they are not actually being used.

**Comment by lolz0r** [comment]
It looks like an easy enough fix is to just comment out lines which require cunn and cutorch in cases when you only want to run in CPU mode. 

It appears that the CPU mode works well enough until the user wants to do truly large images (>~3K) then the same segfault that happens in neural-style happens here. See bug:
https://github.com/jcjohnson/neural-style/issues/24

**Comment by kaishengtai** [comment]
Fixed the cunn/cutorch include in the latest commit. I'll have to look into that segfault you mentioned.

**Comment by anastasiuspernat** [comment]
This bug really belonged to Torch/nn and must have been fixed with my recent pull request
https://github.com/torch/nn/pull/443

Hope it finally works on big images! (Torch must be compiled from source and reinstalled to fix it)

**Comment by arnwas** [comment]
Pity that the cpu mode only uses one core!

**Comment by lolz0r** [comment]
@arnwas Try changing which BLAS you use when you compile torch - intel MKL is best if you can get access to it.
