### ISSUE TITLE
Run in GPU mode?

### ISSUE THREAD

**Issue by Bolei-Di** [kaishengtai/neuralart#17]
I followed the steps and installed everything you've listed, but I'm not able to run it in GPU mode (which will be much faster, right?). It said this when I tried to run it:

qlua: main.lua:40: module 'cutorch' not found:
    no field package.preload['cutorch']
    no file '/Users/boleidi/.luarocks/share/lua/5.1/cutorch.lua'
    no file '/Users/boleidi/.luarocks/share/lua/5.1/cutorch/init.lua'
    no file '/Users/boleidi/torch/install/share/lua/5.1/cutorch.lua'
    no file '/Users/boleidi/torch/install/share/lua/5.1/cutorch/init.lua'
    no file './cutorch.lua'
    no file '/Users/boleidi/torch/install/share/luajit-2.1.0-alpha/cutorch.lua'
    no file '/usr/local/share/lua/5.1/cutorch.lua'
    no file '/usr/local/share/lua/5.1/cutorch/init.lua'
    no file '/Users/boleidi/.luarocks/lib/lua/5.1/cutorch.so'
    no file '/Users/boleidi/torch/install/lib/lua/5.1/cutorch.so'
    no file './cutorch.so'
    no file '/usr/local/lib/lua/5.1/cutorch.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: at 0x01025bd1d0
    [C]: in function 'require'
    main.lua:40: in main chunk

It did run in cpu mode.
Here's my graphic card model: NVIDIA GeForce GT 750M 2048 MB
And I just installed CUDA 7.5

Could you help figure out where the problem is?

**Comment by hughperkins** [comment]
Did you install 'cutorch'?

**Comment by kaishengtai** [comment]
Installing `cutorch` should fix this:

```
luarocks install cutorch
```
