### ISSUE TITLE
The reference of the Total Variation Norm Algorithm

### ISSUE THREAD

**Issue by marvin521** [kaishengtai/neuralart#18]
closed...

**Comment by kaishengtai** [comment]
For reference: https://en.wikipedia.org/wiki/Total_variation_denoising

**Comment by kmul00** [comment]
@kaishengtai 
Hi,

In the original paper by Gatys *et al*  I didn't come across **total variation regularizer** in the loss function. However it is there in most implementations. Was it inspired from some other paper ?
