### ISSUE TITLE
never ending program 

### ISSUE THREAD

**Issue by VincentCusson** [kaishengtai/neuralart#25]
Hi,

I manage to download everything. I use macOSx with cpu and everything run just fine but after the 500th iteration, nothing happens.I now have 20 iterations previews (pictures). Is the last one the final product or is there a final rendering or something ? 

thanks a lot for your help

**Comment by yossibiton** [comment]
The default number of iterations is 500, so thats why the program ends after 500 iterations.
The output images of each iteration go to 'frames' folder.
