### ISSUE TITLE
CPU support

### ISSUE THREAD

**Issue by allanino** [kaishengtai/neuralart#3]
It would be nice to have CPU support, as the memory requirements are quite huge, preventing us to train larger images (I have a GTX 965M with 2 GB and I can't train images larger than 480 px).

I know it will be much slower, but at least it will be _possible_ to train larger images. Besides that, It will also allow people without a GPU to try it.

Do you think this is possible?

**Comment by namp** [comment]
A new implementation which support CPU has appeared here

https://github.com/jcjohnson/neural-style

**Comment by kaishengtai** [comment]
@allanino CPU support is not straightforward to implement with the version of the Inception architecture used here (due to the local response normalization layers). I recommend trying out the other implementation as suggested by @namp.

**Comment by allanino** [comment]
Thanks @kaishengtai. 

I tried @namp's suggestion and got it to work.
