### ISSUE TITLE
sudo luarocks install inn error！

### ISSUE THREAD

**Issue by H0icky** [kaishengtai/neuralart#4]
sudo luarocks install inn
Error: No results matching query were found.
I cant use luarocks to install inn or loadcaffe that mentions in https://github.com/jcjohnson/neural-style

**Comment by Kaixhin** [comment]
If you're having issues with `luarocks` then check https://github.com/torch/nngraph/issues/52. You will need to install `inn` for the code in this repo, but not `loadcaffe`.

**Comment by kaishengtai** [comment]
@H0icky Try installing Torch/Luarocks from http://torch.ch/. They maintain their own manifest that contains modules not in the www.luarocks.org manifest.

**Comment by H0icky** [comment]
@Kaixhin @kaishengtai  Thank you. It works：）
