### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by leongatys** [kaishengtai/neuralart#7]
Maybe try our normalised VGG network for better results: https://bethgelab.org/deepneuralart/

Best
Leon

**Comment by dribnet** [comment]
+1

I also think it would be great to have an option to use their normalized [caffe VGG Network](https://bethgelab.org/media/uploads/deeptextures/vgg_normalised.caffemodel). Happy to contribute and/or do testing on this.

**Comment by kaishengtai** [comment]
@leongatys Thanks for the great work!

@dribnet Absolutely -- that would be a great option to have. Please feel free to submit a pull request if you get it working.

**Comment by kaishengtai** [comment]
I've added support for the normalized VGG network. Works like a charm.
